/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ch_szclsb_orbis_math_jni_JniVectorAPI */

#ifndef _Included_ch_szclsb_orbis_math_jni_JniVectorAPI
#define _Included_ch_szclsb_orbis_math_jni_JniVectorAPI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ch_szclsb_orbis_math_jni_JniVectorAPI
 * Method:    cAdd
 * Signature: (I[F[F[F)V
 */
JNIEXPORT void JNICALL Java_ch_szclsb_orbis_math_jni_JniVectorAPI_cAdd
  (JNIEnv *, jclass, jint, jfloatArray, jfloatArray, jfloatArray);

/*
 * Class:     ch_szclsb_orbis_math_jni_JniVectorAPI
 * Method:    cSub
 * Signature: (I[F[F[F)V
 */
JNIEXPORT void JNICALL Java_ch_szclsb_orbis_math_jni_JniVectorAPI_cSub
  (JNIEnv *, jclass, jint, jfloatArray, jfloatArray, jfloatArray);

/*
 * Class:     ch_szclsb_orbis_math_jni_JniVectorAPI
 * Method:    cMul
 * Signature: (I[F[F[F)V
 */
JNIEXPORT void JNICALL Java_ch_szclsb_orbis_math_jni_JniVectorAPI_cMul__I_3F_3F_3F
  (JNIEnv *, jclass, jint, jfloatArray, jfloatArray, jfloatArray);

/*
 * Class:     ch_szclsb_orbis_math_jni_JniVectorAPI
 * Method:    cMul
 * Signature: (I[F[FF)V
 */
JNIEXPORT void JNICALL Java_ch_szclsb_orbis_math_jni_JniVectorAPI_cMul__I_3F_3FF
  (JNIEnv *, jclass, jint, jfloatArray, jfloatArray, jfloat);

/*
 * Class:     ch_szclsb_orbis_math_jni_JniVectorAPI
 * Method:    cDot
 * Signature: (I[F[F)F
 */
JNIEXPORT jfloat JNICALL Java_ch_szclsb_orbis_math_jni_JniVectorAPI_cDot
  (JNIEnv *, jclass, jint, jfloatArray, jfloatArray);

/*
 * Class:     ch_szclsb_orbis_math_jni_JniVectorAPI
 * Method:    cEquals
 * Signature: (I[F[FF)Z
 */
JNIEXPORT jboolean JNICALL Java_ch_szclsb_orbis_math_jni_JniVectorAPI_cEquals
  (JNIEnv *, jclass, jint, jfloatArray, jfloatArray, jfloat);

#ifdef __cplusplus
}
#endif
#endif
