/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ch_szclsb_orbis_math_jni_Matrix4f */

#ifndef _Included_ch_szclsb_orbis_math_jni_Matrix4f
#define _Included_ch_szclsb_orbis_math_jni_Matrix4f
#ifdef __cplusplus
extern "C" {
#endif
#undef ch_szclsb_orbis_math_jni_Matrix4f_SIZE
#define ch_szclsb_orbis_math_jni_Matrix4f_SIZE 16L
/*
 * Class:     ch_szclsb_orbis_math_jni_Matrix4f
 * Method:    cEqualsC
 * Signature: ([F[FF)Z
 */
JNIEXPORT jboolean JNICALL Java_ch_szclsb_orbis_math_jni_Matrix4f_cEqualsC
  (JNIEnv *, jclass, jfloatArray, jfloatArray, jfloat);

/*
 * Class:     ch_szclsb_orbis_math_jni_Matrix4f
 * Method:    cAdd
 * Signature: ([F[F[F)V
 */
JNIEXPORT void JNICALL Java_ch_szclsb_orbis_math_jni_Matrix4f_cAdd
  (JNIEnv *, jclass, jfloatArray, jfloatArray, jfloatArray);

/*
 * Class:     ch_szclsb_orbis_math_jni_Matrix4f
 * Method:    cSub
 * Signature: ([F[F[F)V
 */
JNIEXPORT void JNICALL Java_ch_szclsb_orbis_math_jni_Matrix4f_cSub
  (JNIEnv *, jclass, jfloatArray, jfloatArray, jfloatArray);

/*
 * Class:     ch_szclsb_orbis_math_jni_Matrix4f
 * Method:    cMul
 * Signature: ([F[F[F)V
 */
JNIEXPORT void JNICALL Java_ch_szclsb_orbis_math_jni_Matrix4f_cMul___3F_3F_3F
  (JNIEnv *, jclass, jfloatArray, jfloatArray, jfloatArray);

/*
 * Class:     ch_szclsb_orbis_math_jni_Matrix4f
 * Method:    cMul
 * Signature: ([FF[F)V
 */
JNIEXPORT void JNICALL Java_ch_szclsb_orbis_math_jni_Matrix4f_cMul___3FF_3F
  (JNIEnv *, jclass, jfloatArray, jfloat, jfloatArray);

/*
 * Class:     ch_szclsb_orbis_math_jni_Matrix4f
 * Method:    cMulElem
 * Signature: ([F[F[F)V
 */
JNIEXPORT void JNICALL Java_ch_szclsb_orbis_math_jni_Matrix4f_cMulElem
  (JNIEnv *, jclass, jfloatArray, jfloatArray, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif
